export const pageLinks = {
  home: "/",
  docs: "/docs",
  introduction: "/graphql/",
  pricing: "/pricing",
  // about: "/about",
  contact: "/contact",
  configGenerator: "/app/config",
  contributors: "/docs/contribution-guidelines",
  privacyPolicy: "/privacy/",
  // enterprise: "/enterprise",
  releases: "/releases",
  blog: "/blog",
  about: "/about",
}
