name: Bug report
description: Create a bug report to help us improve Tailcall
title: "[bug]: "
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to fill out this bug report.
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current behavior
    description: A concise description of what you're experiencing and what you expect
    placeholder: |
      When I do <X>, <Y> happens and I see the error message attached below:
      ```...```
      What I expect is <Z>
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Add steps to reproduce this behaviour, include console or network logs and screenshots
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true

- type: dropdown
  id: repository
  attributes:
    label: Repository
    options:
        - tailcall
        - tailcallhq.github.io
        - homebrew-tailcall
        - tailcall-on-aws
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      Please add the respective Label to the Issue