schema: |
  schema @server @upstream(baseURL: "https://jsonplaceholder.typicode.com") {
    query: Query
  }

  type Address {
    city: String
    geo: Geo
    street: String
    suite: String
    zipcode: String
  }

  type Company {
    bs: String
    catchPhrase: String
    name: String
  }

  type Geo {
    lat: String
    lng: String
  }

  type Photo {
    albumId: Int
    id: Int
    thumbnailUrl: String
    title: String
    url: String
  }

  type Post {
    body: String
    id: Int
    title: String
    userId: Int
    user: User @call(path: "/users/{{.args.userId}}")
  }

  type Comment {
    body: String
    email: String
    id: Int
    name: String
    postId: Int
    post: Post @call(path: "/posts/{{.args.postId}}")
  }

  type Query {
    comment(id: Int!): Comment @http(path: "/comments/{{.args.id}}")
    comments: [Comment] @http(path: "/comments")
    photo(id: Int!): Photo @http(path: "/photos/{{.args.id}}")
    photos: [Photo] @http(path: "/photos")
    post(id: Int!): Post @http(path: "/posts/{{.args.id}}")
    posts: [Post] @http(path: "/posts")
    todo(id: Int!): Todo @http(path: "/todos/{{.args.id}}")
    todos: [Todo] @http(path: "/todos")
    user(id: Int!): User @http(path: "/users/{{.args.id}}")
    users: [User] @http(path: "/users")
  }

  type Todo {
    completed: Boolean
    id: Int
    title: String
    userId: Int
    user: User @call(path: "/users/{{.args.userId}}")
  }

  type User {
    address: Address
    company: Company
    email: String
    id: Int
    name: String
    phone: String
    username: String
    website: String
    posts: [Post] @call(path: "/posts?userId={{.args.id}}")
    todos: [Todo] @call(path: "/todos?userId={{.args.id}}")
  }

types:
  Address:
    city: "String"
    geo: "Geo"
    street: "String"
    suite: "String"
    zipcode: "String"
  Company:
    bs: "String"
    catchPhrase: "String"
    name: "String"
  Geo:
    lat: "String"
    lng: "String"
  Photo:
    albumId: "Int"
    id: "Int"
    thumbnailUrl: "String"
    title: "String"
    url: "String"
  Post:
    body: "String"
    id: "Int"
    title: "String"
    userId: "Int"
    user: "User"
  Comment:
    body: "String"
    email: "String"
    id: "Int"
    name: "String"
    postId: "Int"
    post: "Post"
  Query:
    comment: "Comment"
    comments: "[Comment]"
    photo: "Photo"
    photos: "[Photo]"
    post: "Post"
    posts: "[Post]"
    todo: "Todo"
    todos: "[Todo]"
    user: "User"
    users: "[User]"
  Todo:
    completed: "Boolean"
    id: "Int"
    title: "String"
    userId: "Int"
    user: "User"
  User:
    address: "Address"
    company: "Company"
    email: "String"
    id: "Int"
    name: "String"
    phone: "String"
    username: "String"
    website: "String"
    posts: "[Post]"
    todos: "[Todo]"

queries:
  comment: "/comments/{{.args.id}}"
  comments: "/comments"
  photo: "/photos/{{.args.id}}"
  photos: "/photos"
  post: "/posts/{{.args.id}}"
  posts: "/posts"
  todo: "/todos/{{.args.id}}"
  todos: "/todos"
  user: "/users/{{.args.id}}"
  users: "/users"
