import type {Metadata} from "next"
import {Space_Grotesk, Space_Mono} from "next/font/google"
import Footer from "@/components/shared/Footer"
import "./globals.css"
import Header from "@/components/shared/Header"

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "700"],
  display: "swap",
})
const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <style>{`
        html {
          font-family: ${spaceGrotesk.style.fontFamily};
        }
        code, pre {
          font-family: ${spaceMono.style.fontFamily}!important;
        }
      `}</style>
      <body className={spaceGrotesk.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
